  <link rel="stylesheet" href="<?=WEBSITE;?>/foundation-4.3.2/css/foundation.css" />
  



  <!-- // webicons css -->
<!--   <link rel="stylesheet" type="text/css" href="<?=WEBSITE;?>/css/general_foundicons.css" media="all">  -->
<!--   <link rel="stylesheet" type="text/css" href="<?=WEBSITE;?>/css/social_foundicons.css" media="all">  -->

<style>
	[data-magellan-expedition]{
		padding:0;
	}
	figure{
		margin:0
	}
</style>