<?

$mainOrbitContent = array(
	
	array(
		"path" => "/img/wide/classic_4748.jpg",
		"caption" => "Classic brittle. Hazelnuts, organic fair trade coffee beans, organic peanuts, rock salt. Photo: <em><a href='http://www.nadiachaudhury.com'>Nadia Chaudhury</a></em>"
	),
	array(
		"path" => "/img/wide/veracruz_4513.jpg",
		"caption" => "Veracruz brittle. Ancha chillies, bittersweet chocolate, cilantro and cinammon. Photo: <em><a href='http://www.nadiachaudhury.com'>Nadia Chaudhury</a></em>"
	),
	array(
		"path" => "/img/wide/hibiscus_1121.jpg",
		"caption" => "Candied hibiscus flowers."
	),
	array(
		"path" => "/img/wide/kaz_4586.jpg",
		"caption" => "Inspired by the menu at Kaz An Nou in Fort Greene. Candied limes and hot peppers, pistachios, rum... Photo: <em><a href='http://www.nadiachaudhury.com'>Nadia Chaudhury</a></em>"
	),
	array(
		"path" => "/img/wide/lime_1123.jpg",
		"caption" => "Candied limes.</a></em>"
	),
/*
	array(
		"path" => "/img/wide/fruity_fab_4484.jpg",
		"caption" => "Fruity and Fabulous. Sour cherries, cashews, and allspice. Photo: <em><a href='http://www.nadiachaudhury.com'>Nadia Chaudhury</a></em>" 
	),
*/
	array(
		"path" => "/img/wide/xmas-ham_4533.jpg",
		"caption" => "Seasonal Xmas Ham featuring bacon, candied pineapple, and cloves. Photo: <em><a href='http://www.nadiachaudhury.com'>Nadia Chaudhury</a></em>" 
	),
	array(
		"path" => "/img/wide/peppers_1143.jpg",
		"caption" => "Candied jalapeño and habañero peppers." 
	)
	
);



$products['brittle'] = array(

	(object)array(
		"id" => 1,
		"type" => "BRITTLE",
		"name" => "Classic Brittle",
		"size" => "7oz bag",
		"price" => 9,
		"desc" => "Organic peanuts, hazelnuts, and fair-trade coffee beans. Our first flavor, originally made to accompany a crème brûlée. We discovered it’s also delicious as part of a decadent breakfast.",
		"img" => array(
			"/img/square/products/classic1.jpg"
		)
	),
	(object)array(
		"id" => 2,
		"type" => "BRITTLE",
		"name" => "Veracruz Brittle",
		"size" => "7oz bag",
		"price" => 9,
		"desc" => "Inspired by the popular savory sauce south of the border, we take roasted ancha and hot peppers and dress them with bittersweet chocolate, cinnamon, and cilantro.",
		"img" => array(
			"/img/square/products/veracruz1.jpg"
		)
	),
	(object)array(
		"id" => 3,
		"type" => "BRITTLE",
		"name" => "Kaz An Nou Brittle",
		"size" => "7oz bag",
		"price" => 11,
		"desc" => "Inspired by the menu of the Fort Greene restaurant of the same name. Rum-infused pistachios mingle with our candied hot peppers and limes. Finished with a bouquet of caribbean spices.",
		"img" => array(
			"/img/square/products/kaz1.jpg"
		)
	),
	(object)array(
		"id" => 4,
		"type" => "BRITTLE",
		"name" => "Bourbon Whiskey Brittle",
		"size" => "7oz bag",
		"price" => 10,
		"desc" => "For our bourbon-loving friends, we infuse Kentucky and Tennessee whiskeys into our nuts before roasting and finish with a smokey bourbon reduction.",
		"img" => array(
			"/img/square/products/bourbon1.jpg"
		)
	),
	(object)array(
		"id" => 5,
		"type" => "BRITTLE",
		"name" => "Xmas Ham Brittle",
		"size" => "7oz bag",
		"price" => 10,
		"desc" => "Our seasonal Xmas Ham flavor. Crispy bacon, candied pineapple, and clove.",
		"img" => array(
			"/img/square/products/xmas-ham1.jpg"
		)
	),
	(object)array(
		"id" => 6,
		"type" => "BRITTLE",
		"name" => "Fruity and Fabulous Brittle",
		"size" => "7oz bag",
		"price" => 9,
		"desc" => "Antonia loves all things tart, and this is her brittle baby: sour cherries, cashews, and allspice.",
		"img" => array(
			"/img/square/products/fruity-and-fabulous1.jpg"
		)
	)
);


$products['sweets'] = array(
	(object)array(
		"id" => 7,
		"type" => "SWEETS",
		"name" => "Candied Hibiscus Flowers",
		"size" => "4oz mason jar",
		"price" => 5.50,
		"desc" => "Hand-candied hibiscus flowers, tart and sweet. Try not to eat the whole jar at once.",
		"img" => array(
			"/img/square/products/hibiscus1.jpg"
		)
	),
	(object)array(
		"id" => 8,
		"type" => "SWEETS",
		"name" => "Candied Limes",
		"size" => "4oz mason jar",
		"price" => 6,
		"desc" => "Thinly-sliced and lovingly boiled in sugar until they earn the triple crown of taste: sweet, tart, and bitter. Find them in our Kaz An Nou brittle flavor.",
		"img" => array(
			"/img/square/products/lime1.jpg"
		)
	),
	(object)array(
		"id" => 9,
		"type" => "SWEETS",
		"name" => "Candied Roses",
		"size" => "4oz mason jar",
		"price" => 7,
		"desc" => "Whole moroccan roses, trimmed and carefully candied. We use the whole flower, including the slightly bitter center, so if you like bitter flavors like Aperol or Campari you'll dig this.",
		"img" => array(
			"/img/square/products/rose1.jpg"
		)
	),
	(object)array(
		"id" => 10,
		"type" => "SWEETS",
		"name" => "Candied Hot Peppers",
		"size" => "4oz mason jar",
		"price" => 6,
		"desc" => "Jalapeños, habañeros, and other hot peppers sliced into delicate ribbons and candied. Sweet and explosively spicy. We make these for our Kaz An Nou brittle flavor.",
		"img" => array(
			"/img/square/products/peppers1.jpg"
		)
	)
);


$products['syrups'] = array(
	(object)array(
		"id" => 11,
		"type" => "SYRUPS",
		"name" => "Hibiscus Syrup",
		"size" => "4oz mason jar",
		"price" => 6,
		"desc" => "Extracted from our candied hibiscus. Add a teaspon to white wine or champagne for a twist on a <a href='http://en.wikipedia.org/wiki/Kir_(cocktail)'>kir</a>. Mix with seltzer to make seltzer. Use in salad dressings, margaritas, or just sip it by the spoonful.",
		"img" => array(
			"/img/square/products/hibiscus-syrup-4oz-mason-side.jpg"
		)
	),
	(object)array(
		"id" => 12,
		"type" => "SYRUPS",
		"name" => "Bitter Lime Syrup",
		"size" => "4oz mason jar",
		"price" => 6,
		"desc" => "Extracted from our candied limes. Use in marinades or salad dressings, or add to lime-based drinks for an interesting bitter edge.",
		"img" => array(
			"/img/square/products/lime-syrup-4oz-mason-side.jpg"
		)
	),
	(object)array(
		"id" => 13,
		"type" => "SYRUPS",
		"name" => "Bitter Rose Syrup",
		"size" => "4oz mason jar",
		"price" => 6.50,
		"desc" => "Extracted from our candied roses. Mix with vodka and use as a substitute for Campari or Aperol in cocktails. Great in marinades for chicken and pork. Also makes an exotic soda when mixed with seltzer.",
		"img" => array(
			"/img/square/products/rose-syrup-4oz-mason-side.jpg"
		)
	),
	(object)array(
		"id" => 14,
		"type" => "SYRUPS",
		"name" => "Hot Pepper Syrup",
		"size" => "4oz mason jar",
		"price" => 5.50,
		"desc" => "Extracted from our candied hot peppers. Used sparingly, gives a kick to margaritas, martinis, and other cocktails. Brightens stir-fries, heats up roasted or barbecued meats and veggies.",
		"img" => array(
			"/img/square/products/pepper-syrup-4oz-mason-side.jpg"
		)
	)
);




?>