<?

$mainOrbitContent = array(
	
	array(
		"path" => "/img/wide/classic_4748.jpg",
		"caption" => "Classic brittle. Hazelnuts, organic fair trade coffee beans, organic peanuts, rock salt. Photo: <em><a href='http://www.nadiachaudhury.com'>Nadia Chaudhury</a></em>"
	),
	array(
		"path" => "/img/wide/veracruz_4513.jpg",
		"caption" => "Veracruz brittle. Ancha chillies, bittersweet chocolate, cilantro and cinammon. Photo: <em><a href='http://www.nadiachaudhury.com'>Nadia Chaudhury</a></em>"
	),
	array(
		"path" => "/img/wide/hibiscus_1121.jpg",
		"caption" => "Candied hibiscus flowers. No artificial color!"
	),
	array(
		"path" => "/img/wide/kaz_4586.jpg",
		"caption" => "Inspired by the menu at Kaz An Nou in Fort Greene. Candied limes and hot peppers, pistachios, rum... Photo: <em><a href='http://www.nadiachaudhury.com'>Nadia Chaudhury</a></em>"
	),
	array(
		"path" => "/img/wide/lime_1123.jpg",
		"caption" => "Candied limes.</a></em>"
	),
/*
	array(
		"path" => "/img/wide/fruity_fab_4484.jpg",
		"caption" => "Fruity and Fabulous. Sour cherries, cashews, and allspice. Photo: <em><a href='http://www.nadiachaudhury.com'>Nadia Chaudhury</a></em>" 
	),
*/
	array(
		"path" => "/img/wide/xmas-ham_4533.jpg",
		"caption" => "Seasonal Xmas Ham featuring bacon, candied pineapple, and cloves. Photo: <em><a href='http://www.nadiachaudhury.com'>Nadia Chaudhury</a></em>" 
	),
	array(
		"path" => "/img/wide/peppers_1143.jpg",
		"caption" => "Candied jalapeño and habañero peppers." 
	)
	
);





?>