<header>

			<div class="row">
				
				<div class="large-2 columns">
					<a href="<?=WEBSITE;?>"><img src="img/brittle-barn-logo.gif"></a>
				</div>

				<div class="large-7 columns top-padding">
					
					<div data-magellan-expedition="fixed">
					  <dl class="sub-nav">
					    <dd data-magellan-arrival="brittle"><a href="/#brittle">Brittle</a></dd>
					    <dd data-magellan-arrival="sweets"><a href="/#sweets">Sweets</a></dd>
					    <dd data-magellan-arrival="syrups"><a href="/#syrups">Syrups</a></dd>
					    <dd data-magellan-arrival="special"><a href="/#special">Special Orders</a></dd>
					    <dd data-magellan-arrival="contact"><a href="/#contact">Contact Us</a></dd>
					  </dl>
					</div>
					    

				</div>

				<div class="large-3 columns text-right">
					
					<i class="general foundicon-cart shop-icon" rel='go-to-cart'></i>

					<span class="connect">connect</span>

					<ul class="icon-grid">
					  <li><i class="social foundicon-twitter"></i></li>
				      <li><i class="social foundicon-facebook"></i></li>
				      <li><i class="social foundicon-instagram"></i></li>
				    </ul>

				</div>
			
			</div>

	</header>